import "./globals.css";
import "./layout.css";
import { Inter } from "next/font/google";

import Banner from "@/components/banner/Banner";
import Branding from "@/components/branding/Branding";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner />
        <Branding />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
